### ISSUE TITLE
Block Service

### ISSUE THREAD

**Issue by ninanomenon** [drswork/go-twitter#10]
Hello,

I was already on the verge of forking the lib myself in order to maintain it more actively than is currently the case. But then I just saw that you guys are already trying.

My motivation was, among other things, to implement the block service. I discovered that someone had already made the effort: 
https://github.com/dghubble/go-twitter/pull/149

Maybe you could merge it here?

**Comment by drswork** [comment]
Sure, I’ll take a look at that this weekend

**Comment by drswork** [comment]
Done, grabbed dghubble#149 and merged it in.

**Comment by drswork** [comment]
I gave the block service docs a scan and saw that List and IDs were missing, so those are added in now too.

**Comment by ninanomenon** [comment]
Oh wow, that was fast. Thanks a lot!
